### PR TITLE
Adding mount_ensure parameter to logical volume

### PR DESCRIPTION
**Pull request by GiooDev**
Hi,
I've add a little functionality to allow the creation of a logical volume without mounting it automatically. In some cases, I'd like to create a logical volume but not mounted by default (ex. if I use this logical volume as a disk in Virtual Machine).

So I add a mount_ensure parameter to logical_volume.pp to allow the usage of the Mount resource with ensure => mount, unmounted, present, absent (default: mounted).

My example used to test it:
```
# LVM
class { 'lvm':
  volume_groups    => {
    'vg00' => {
      physical_volumes => [ '/dev/sda2', ],
      logical_volumes  => {
        'present'   => {
                    'size'         => '1G',
                    'mountpath'    => '/mnt/present',
                    'fs_type'      => 'xfs',
                    'mount_ensure' => 'present',
                    },
        'unmounted'  => {
                    'size'         => '1G',
                    'fs_type'      => 'xfs',
                    'mount_ensure' => 'unmounted',
                    },
        'absent'  => {
                    'size'         => '1G',
                    'fs_type'      => 'xfs',
                    'mount_ensure' => 'absent',
                    },
        'mounted' => {
                    'size'         => '1G',
                    'fs_type'      => 'xfs',
                    'mountpath'    => '/mnt/mounted',
                    'mount_ensure' => 'mounted',
                    },
      },
    },
  },
}
```
https://docs.puppetlabs.com/references/latest/type.html#mount-attribute-ensure

Warning, there is still an issue when trying to resize with unmounted partitions. The logical volume is resized but not the filesystem, it cause an error during puppet apply.

Thanks.
Julien Georges <julien.georges@atos.net>

### CODE REVIEW

**Comment by bmjen** [comment]
@GiooDev Thanks for the contribution! This seems like a really useful feature. There are a few things that need to be worked out. The issue you mentioned with resizing LVMs, a solution needs to be created where you don't have mismatched logical volume and filesystem sizes. Perhaps prevent the user from resizing if the filesystem isn't mounted? A change like this would also need some tests. The other items include a rebase of your branch, and also the commits should be appropriately squashed before it can be merged.

Thanks!

**Comment by GiooDev** [comment]
I've updated my fork with the latest sources of your project and now it seems ok to be merged.
I'll try to work on the issue later if I had time to fix this warning.

**Comment by bmjen** [comment]
@GiooDev Thanks! I'll await the fix for the warning or some other solution to the resizing issue before merging. And the commits also need to be squashed prior to merging as well.

**Comment by tphoney** [comment]
ping @GiooDev have you made the changes from @bmjen suggestions. Thanks for your effort.

**Comment by GiooDev** [comment]
Hi, I didn't had the time to really work on this issue. I made some tests but I didn't found a correct solution to solve all my test cases. I'll keep you informed if I found a complete solution.

**Comment by tphoney** [comment]
Any luck on getting time to working on this ?

**Comment by bmjen** [comment]
Thanks for the contribution @GiooDev, please reopen this PR when you get a chance to make the updates and do a rebase.

**Pull request closed without merging**
