### PR TITLE
Allowing ???%FREE to extends volumes while resizing

### PR DESCRIPTION
**Pull request by renato-farias**
The current version does not allow users to auto-resize the lv and the fs to 100%FREE available.

### CODE REVIEW

**Comment by Yamakasi** [comment]
Please accept this pullrequest, it's very needed! Thanks!

**Comment by rbclark** [comment]
One small problem with this pull request is it does break idempotence, on every run I receive `size changed 'xxxG' to '100%FREE'`

**Comment by rbclark** [comment]
Also interesting thing I found when running this is if you need '100%FREE' without this PR you can simply pass in undef to size which will automatically fill the disk.

**Comment by renato-farias** [comment]
> Also interesting thing I found when running this is if you need '100%FREE' without this PR you can simply pass in undef to size which will automatically fill the disk.

Yeap, while creating a new volume it allocates 100% of free space if you set nothing. But the purpose of this PR regards when users try to update/expand the volume. Undef does not expand the volume when it's updated.

**Comment by daveseff** [comment]
+1 to this. I just got bit by this limitation.

**Comment by baurmatt** [comment]
This would be really helpful! :) Can we get rid of the `size changed ...` on every run?

**Comment by baurmatt** [comment]
Hey @renato-farias, what happend? ;) Are you planing to open a new PR for this? If not, please let me know and I will give it a shot.

**Comment by renato-farias** [comment]
> Hey @renato-farias, what happend? ;) Are you planing to open a new PR for this? If not, please let me know and I will give it a shot.

Hi @baurmatt , give it a shot, I don't have the dev environment here anymore. Thanks.

**Pull request closed without merging**
