### PR TITLE
Added support for LVM Thin Volumes

### PR DESCRIPTION
**Pull request by glorpen**

### CODE REVIEW

**Comment by glorpen** [comment]
Can someone look at this PR? I think it is simple enough change.

**Comment by glorpen** [comment]
Can I interest you in this PR? :) @pmcmaw @willmeek

**Comment by pmcmaw** [comment]
Hey @glorpen 

The change looks fine :-), would you be able to add some testing around the new functionality please :-)

**Comment by glorpen** [comment]
I've added some tests. I've tried to make one for autorequire but... lack of knowledge about rspec stopped me.

**Comment by glorpen** [comment]
@pmcmaw is it enough for tests?

**Pull request merged**
