### PR TITLE
Fix manage_pkg scope

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by raphink** [comment]
@hunner @davids could this be merged please?

**Comment by mcanevet** [comment]
@DavidS thanks,
would it be possible to release `0.6.1` as the `0.6.0` just don't work with `strict_variables`?

**Comment by DavidS** [comment]
Preparations started at
https://github.com/puppetlabs/puppetlabs-lvm/pull/142

**Comment by HelenCampbell** [comment]
Version 0.7.0 now released @mcanevet . Thanks!

**Pull request merged**
