### PR TITLE
resolve /dev/disk/by-path/xxxx symlinks to block devices

### PR DESCRIPTION
**Pull request by timhughes**
new parameter to tell volume_group Type to resolve PV symlinks to real devices, and override insync? method to do this

### CODE REVIEW

**Comment by tphoney** [comment]
Can you please rebase, this is why travisCI maybe failing for this PR. I tested this with #168  
apologies for the inconvenience.

**Comment by bmjen** [comment]
Fixes: https://tickets.puppetlabs.com/browse/MODULES-3991

**Comment by hunner** [comment]
Could the commits be squashed? Also please include "(MODULES-3991)" at the beginning of the commit message for future tracking.

**Comment by timhughes** [comment]
These tests pass if I change the version of rspec to ~> 3.4.0.  

https://github.com/ruby/rake/issues/116

**Comment by bmjen** [comment]
Thanks @timhughes and @lukebigum !

**Pull request merged**
