### PR TITLE
Fix bad regexp

### PR DESCRIPTION
**Pull request by rabbitt**
regular expression was incorrectly using character classes and matching strings like: 100( or 100v etc.

### CODE REVIEW

**Comment by tphoney** [comment]
Thanks for spotting this, could you add a test to reflect the problem seen. This will prevent the issue from resurfacing.

**Comment by rabbitt** [comment]
test added.

**Comment by tphoney** [comment]
Sorry, i think the unit tests are failing.

**Comment by rabbitt** [comment]
Sorry - I didn't realize you were supporting ruby 1.8.7. I'll switch to using hash rockets in the patch.

**Comment by rabbitt** [comment]
What's the good word on this? :-)

**Comment by tphoney** [comment]
Sorry about the delay, thanks for the work.

**Pull request merged**
