### PR TITLE
Confine lvm providers to linux (MODULES-6449)

### PR DESCRIPTION
**Pull request by hpcprofessional**

### CODE REVIEW

**Comment by jessereynolds** [comment]
Without this PR, this module is unusable for any organisation that has any Windows machines managed by puppet.

**Comment by lesinigo** [comment]
This is also causing Facter errors on FreeBSD which we didn't have when using version 0.9.0:
```
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Facter: error while resolving custom facts in /var/puppet/lib/facter/lvm_support.rb: execution of command "vgs -o name --noheadings 2>/dev/null" failed: command not found.
Info: Applying configuration version '[63f1f3c] upgrade module puppetlabs/lvm (0.9.0 -> 1.0.0)'
Notice: Applied catalog in 1.93 seconds
```

**Comment by rodolfosalgado** [comment]
Any news when will this be merged ?

**Comment by daveseff** [comment]
+1

**Comment by HelenCampbell** [comment]
Thanks @hpcprofessional !

**Pull request merged**
