### PR TITLE
(MODULES-9004) Resize XFS file system by mount point, not by volume

### PR DESCRIPTION
**Pull request by foofoo-2**
Hi everyone,

This PR should solve https://tickets.puppetlabs.com/browse/MODULES-9004 by using the mount point to resize an XFS file system instead of the volume. Without this change, file system resizing does not work with newer xfs versions (e.g. 4.19.0 under RHEL8).

As it is my first contribution, feel free to tell me if I missed something.

Thanks in advance!

### CODE REVIEW

**Comment by lionce** [comment]
Hello @foofoo-2 , in order to merge this change, we need to make sure that these changes are fixing the issue. Would you please test this on your server and let us know the status? Thanks in advance!

**Comment by foofoo-2** [comment]
Hi @lionce,

I did a quick test on my server and it looks good with the proposed change. Please find here an example while increasing the size of a logical from 9G to 10G:

```
# Server information
[root@rhel8-test ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.0 (Ootpa)
[root@rhel8-test ~]# uname -a
Linux rhel8-test.mydomain 4.18.0-80.el8.x86_64 #1 SMP Wed Mar 13 12:02:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

# Before Puppet run
[root@rhel8-test ~]# lvs /dev/vrhvg/homelv
  LV     VG    Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  homelv vrhvg -wi-ao---- 9.00g
[root@rhel8-test ~]# df -h /home
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/vrhvg-homelv  9.0G   94M  9.0G   2% /home

# Puppet run
[root@rhel8-test ~]# puppet agent -t
...
Notice: /Stage[main]/Disks/Disks::Osvg::Lv_size[homelv]/Disks::Osvg::Lv[homelv]/Logical_volume[homelv]/size: size changed '9G' to '10G'
Notice: Applied catalog in 7.15 seconds

# After Puppet run
[root@rhel8-test ~]# lvs /dev/vrhvg/homelv
  LV     VG    Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  homelv vrhvg -wi-ao---- 10.00g
[root@rhel8-test ~]# df -h /home
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/vrhvg-homelv   10G  102M  9.9G   1% /home
```

If you need additional information, feel free to ask.

Thanks!

**Comment by lionce** [comment]
@foofoo-2 Many thanks for your prompt response :) 👍 It looks good! 
Thanks again for this fix!

**Comment by foofoo-2** [comment]
Thanks for the quick merge @lionce!

Could you please tell me if I have to do something else to have this fix integrated in an official release of the module and published to the Forge?

**Comment by lionce** [comment]
Hey @foofoo-2 , I'll let you know when the new version is released and published to the Forge with your changes! Thanks

**Comment by lionce** [comment]
Hello @foofoo-2 ,
the new version 1.3.0 i released on forge. Your changes are included! Thank you!

**Pull request merged**
