### PR TITLE
[WIP] Move command execution to within setcode blocks

### PR DESCRIPTION
**Pull request by dylanratcliffe**
This allows for confine statments to work correctly

### CODE REVIEW

**Comment by dylanratcliffe** [comment]
@vchepkov can you please review? RE: [MODULES-6449](https://tickets.puppetlabs.com/browse/MODULES-6449)

**Comment by vchepkov** [comment]
Shall I wait till you finish the test suite? Also curious, what change now require dependency on mount_core ?

**Comment by dylanratcliffe** [comment]
Sorry this last commit should have it fixed. Puppet 6 removes a lot of stuff from Puppet core and moves it out to modules like all the nagios types for example. Mount was also one of them so when upgrade to Puppet 6 you'll need to use the mount module instead of relying on the built in types

**Comment by vchepkov** [comment]
First check, some facts disappeared, not sure if they were useful to begin with, but you asked to test

```
# diff -u before after|grep ^-
--- before	2018-11-10 12:37:55.796311076 +0000
-lvm_pv_0 => /dev/sda2
-lvm_vg_0 => vg0
-lvm_vg_vg0_pvs => /dev/sda2
```

**Comment by vchepkov** [comment]
confinement works fine though. I tested on Solaris, on Linux without lvm

**Comment by vchepkov** [comment]
It appears you call Facter.add from within of Facter.add. Is it allowed?

**Comment by dylanratcliffe** [comment]
Hmm, tests are passing but that doesn't necessarily mean it's working. Possibly Facter.add from within a fact fails silently. Stand by while I refactor more

**Comment by dylanratcliffe** [comment]
@vchepkov Yes all the stuff that was ripped out has been included in the agent packages for now so that everything doesn't totally fall over. I think this might be something to do with cfacter working differently than ruby facter. Trying to work out how to get a proper test suite set up so that I can verify

**Comment by dylanratcliffe** [comment]
Closing in favour of the simpler #193 and the eventual removal of these facts

**Pull request closed without merging**
