### PR TITLE
Ruby231

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@hunner @tphoney could you have a look please

**Comment by ghoneycutt** [comment]
Could someone please merge

**Comment by ghoneycutt** [comment]
Hi, could you please merge this

**Comment by bmjen** [comment]
Thanks @ghoneycutt ! sorry for the delay!

**Comment by ghoneycutt** [comment]
Thank you very much!! Could you please tag a new release.

**Pull request merged**
