### PR TITLE
Adding volumegroup provider for AIX & adding mountgroup parameter 

### PR DESCRIPTION
**Pull request by rmueck**
With this modification one can use volume_group provider under AIX (tested on 6100 & 7100).
Also added the ability to use the mountgroup directive for filesystems (tested on 6100 & 7100)

### CODE REVIEW

**Comment by tphoney** [comment]
Can you please squash these commits. Thanks for your work.

**Comment by rmueck** [comment]
On 21.04.2015 13:36, TP Honey wrote:
>
> Can you please squash these commits. Thanks for your work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/puppetlabs/puppetlabs-lvm/pull/97#issuecomment-94756361>.
>


Hello,

to be honest ...i donno how ..i tried but without success

Sincerely
Ruediger

**Comment by tphoney** [comment]
Squashing commits to view your last commits:
git log --pretty=oneline
To squash the last 2 commits
git rebase --interactive HEAD~2
The read the text, and save. You can view the squash with the log command. 
git push -f origin destination_branch

**Comment by tphoney** [comment]
Hi @rmueck , thanks for the work you have put in to this pull request. However due to inactivity, needing quashed and no tests added this pull request is being closed. If you want to re-submit this PR with the necessary changes, we will gladly look at the new pull request.

https://docs.puppetlabs.com/guides/module_guides/bgtm.html#step-three-module-testing
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Pull request closed without merging**
